version: '3.2'
services:
  master:
    container_name: dst-master
    image: i386/busybox:musl
    working_dir: /opt/dst/bin
    command: ["/usr/local/lib/ld-linux.so.2", "--library-path", "/usr/local/lib", "/opt/dst/bin/dontstarve_dedicated_server_nullrenderer", "-cluster", "Cluster", "-shard", "Master"]
    networks:
      - dst_cluster
    ports:
      - target: 10999
        published: 10999
        protocol: udp
        mode: host
    volumes:
      - type: volume
        source: game-app
        target: /opt/dst
        read_only: true
      - type: volume
        source: game-data
        target: /root/.klei
      - type: volume
        source: game-lib
        target: /usr/local/lib
        read_only: true
        volume:
          nocopy: true
  caves:
    container_name: dst-caves
    image: i386/busybox:musl
    working_dir: /opt/dst/bin
    command: ["/usr/local/lib/ld-linux.so.2", "--library-path", "/usr/local/lib", "/opt/dst/bin/dontstarve_dedicated_server_nullrenderer", "-cluster", "Cluster", "-shard", "Caves"]
    networks:
      - dst_cluster
    ports:
      - target: 11000
        published: 11000
        protocol: udp
        mode: host
    volumes:
      - type: volume
        source: game-app
        target: /opt/dst
        read_only: true
      - type: volume
        source: game-data
        target: /root/.klei
      - type: volume
        source: game-lib
        target: /usr/local/lib
        read_only: true
        volume:
          nocopy: true
  lib:
    container_name: dst-lib
    image: i386/debian:buster-slim
    command: ["/bin/bash", "/root/libraries/download-libraries.sh"]
    volumes:
     - type: volume
       source: game-lib
       target: /root/libraries
     - type: bind
       source: ./download-libraries.sh
       target: /root/libraries/download-libraries.sh
       read_only: true
  steam:
    container_name: dst-steam
    image: cm2network/steamcmd:root
    working_dir: /home/steam/steamcmd
    command: ["/bin/bash", "/home/steam/download-game.sh"]
    volumes:
      - type: volume
        source: game-app
        target: /home/steam/download
      - type: bind
        source: ./download-game.sh
        target: /home/steam/download-game.sh
        read_only: true
  setup:
    container_name: dst-setup
    image: i386/busybox:musl
    working_dir: /root/game-setup
    command: ["/bin/ash", "/root/game-setup/initialize-data.sh"]
    volumes:
      - type: volume
        source: game-data
        target: /root/game-data
      - type: bind
        source: ./initialize-data.sh
        target: /root/game-setup/initialize-data.sh
        read_only: true
networks:
  dst_cluster:
    driver: bridge
volumes:
  game-app:
  game-data:
  game-lib:
