version: '3.2'
services:
  setup:
    container_name: dst-setup
    image: i386/busybox:musl
    working_dir: /root/game-setup
    command: ["/bin/ash", "/root/game-setup/initialize-data.sh"]
    volumes:
      - type: volume
        source: game-data
        target: /root/game-data
      - type: bind
        source: .
        target: /root/game-setup
        read_only: true
volumes:
  game-data:
