version: '3.2'
services:
  libmachine:
    image: i386/debian:buster-slim
    command: ["/bin/bash", "/root/libraries/download-libraries.sh"]
    volumes:
     - type: bind
       source: /opt/dst-server/game-lib
       target: /root/libraries
