version: '3.2'
services:
  master:
    container_name: dst-master
    image: i386/busybox:musl
    working_dir: /opt/dst/bin
    command: ["/usr/local/lib/ld-linux.so.2", "--library-path", "/usr/local/lib", "/opt/dst/bin/dontstarve_dedicated_server_nullrenderer", "-cluster", "Cluster", "-shard", "Master"]
    networks:
      - dst_cluster
    ports:
      - target: 10999
        published: 10999
        protocol: udp
        mode: host
    volumes:
      - type: bind
        source: /home/ec2-user/game-app
        target: /opt/dst
        read_only: true
      - type: bind
        source: /home/ec2-user/game-data
        target: /root/.klei
      - type: bind
        source: /home/ec2-user/game-lib
        target: /usr/local/lib
        read_only: true
  caves:
    container_name: dst-caves
    image: i386/busybox:musl
    working_dir: /opt/dst/bin
    command: ["/usr/local/lib/ld-linux.so.2", "--library-path", "/usr/local/lib", "/opt/dst/bin/dontstarve_dedicated_server_nullrenderer", "-cluster", "Cluster", "-shard", "Caves"]
    networks:
      - dst_cluster
    ports:
      - target: 11000
        published: 11000
        protocol: udp
        mode: host
    volumes:
      - type: bind
        source: /home/ec2-user/game-app
        target: /opt/dst
        read_only: true
      - type: bind
        source: /home/ec2-user/game-data
        target: /root/.klei
      - type: bind
        source: /home/ec2-user/game-lib
        target: /usr/local/lib
        read_only: true
networks:
  dst_cluster:
    driver: bridge
