version: '3.2'
services:
  steam:
    container_name: dst-steam
    image: cm2network/steamcmd:root
    working_dir: /home/steam/steamcmd
    command: ["/bin/bash", "/home/steam/download-game.sh"]
    volumes:
      - type: volume
        source: game-app
        target: /home/steam/download
      - type: bind
        source: ./download-game.sh
        target: /home/steam/download-game.sh
        read_only: true
volumes:
  game-app:
